spring:
  application:
    name: print-controller
  messages: 
    basename: i18n/messages,i18n/business
server: 
  port: 8335  # web端测试
#  port: 8339  #自个测试
#启用shutdown
endpoints:
  shutdown: 
    enabled: true
    sensitive: false
    path: /clo/shutdown_123
  dubbo: 
    enabled: true

    
management:
  port: 8082
  address: 127.0.0.1
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool

dubbo:
  scan:
#    basePackages: ivg.cn.stock.dubbo.provider
  application:
    id: invengo-api
    name: invengo-api
  registry:
    id: my-registry
    address: multicast://224.5.6.7:1234
  protocol:
    id: dubbo
    name: dubbo
    port: 12346
    status: server
